version: '3'

services:
  app:
    build: . 
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - ./kuroneko/location_db:/app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true